README.md
lib/Gateway.js

When a Command Class is type Meter. In some cases is not a sensor. This metric is a Delta in time, or reset parameter for the Sensor.
There Parameters miss the ccSpecific values, which sets the type of sensor. This change fixes this error

fix: meterType devices missing ccSpecific values

---

lib/ZwaveClient.js

fix: catch errors from zwave driver contructor #61

---

src/components/ControlPanel.vue
src/components/Settings.vue

I added an Export option for nodes.. Currently this export button can help on debugging issues.
Info:
- Per Node Export
- Discreet location no right side, next to node ID
- Output is Json format
Export Screenshot:

Feature: Add Export button to Nodes for Debug reasons

---

lib/Gateway.js

Multiple times happens on notification names during discovery to have a name like:
```
sensor_notification_Power Management_Power Management
```
It would be better if these names where:
```
sensor_notification_Power Management_Motion
```
This tries to avoid using the "duplicate" name by setting on Notifications the propertyKey
Also this happens with betteries, and other endpoints. when duplication happens.  It is good idea to use endpoint number as extension instead of "repeating" the same property name.

[fix] Detail on naming - Notifications  Names

---

lib/Gateway.js

fix: discovery issues caused by spaces in topic

---

lib/Gateway.js

Make Sensors of Notification CC provide translated values to Home assistant.
An example is Motion sensors. While the state is 0 or 8, this is not a nice to look into.
The real values per z-wave specification are idle and 'Motion detection'.
This patch converts the sensor values showin in HASS in human readable form.

[feat] Hass: Add Translation of states list to value_template map and Notification Command Class first to use this

---

lib/Gateway.js
lib/ZwaveClient.js

Add support for propertyKey and property on bugs 109 and 108.
I am looking into a more generic place for this to be applied. As it seems the same issue we faced with notifications exists in multiple places.
in some cases it makes sense to have a reverse order of the propertyKey and property, in order to look better and make sense.
Bugs: #108 #109

[fix] Try to fix bugs 109 and 108

---

docker/Dockerfile.contrib

Yesterday I did some changes to speed up CI runs in zwave-js. One big offender was building the TS sources which essentially built the same packages over and over.
As a result I split the build step into two - one for packaging etc. (`build:full`) and one for small updates (`build`).

fix: run new build:full command to build zwave-js

---

hass/configurations.js

fixes #137 
The Locks uses numbers(integers) instead of boolean with the new driver. update the payload

fix(hass): lock payload and state

---

lib/ZwaveClient.js

Upstream logConfig interface expects the log level to be sent as a number

fix: send loglevel to driver as a number

---

lib/Constants.js
lib/Gateway.js

Upstream has new ConfigManager, lookupMeter is accessible there.

fix: Read meters from ConfigManager

---

docker/Dockerfile.contrib

I guess this could avoid the duplicate config dependencies we're currently seeing. However I couldn't test it since I have no clue how to run the container after executing the command from the docs.
/cc @larstobi 
fixes: #173 
(I hope)

fix: use yarn link instead of yalc in Dockerfile.contrib

---

package-lock.json
package.json

Update to latest zwave-js 6.0.0-beta.0
fixes:
- logging
- Meter updates

[chore] upgrade zwavejs to beta

---

hass/devices.js

This fixes #202 by removing blocking configuration. See the the issue for more information.

fix: remove Thermofloor Z-trm2fx specific configuration (fix #202)

---

lib/ZwaveClient.js

Resolves https://github.com/zwave-js/zwavejs2mqtt/issues/210
The correct fix is to change to a stateless event notification, rather than tracking a stateful value, but this should work as a workaround.

fix: central scene notification argument list changed in Zwave-JS 6.0

---

docker/README.md

First fix: If you cd into "docker", the Dockerfile is present in the same directory. 
Second fix: The branch `feat#startStop` doesn't exist, and most people must want to build master branches.

Fix commands in Dockerfile.contrib steps

---

src/modules/NodeCollection.js

If node values are `null` or `undefined` errors like the following show up in the browser console and the selection of string values for columns in the node table is not available:
```
vue.esm.js?a026:628 [Vue warn]: Error in render: "TypeError: Cannot read property 'header' of null"
found in
---> <VSelect>
<VForm>
<ColumnFilterString> at src/components/nodes-table/ColumnFilterString.vue
```
This PR fixes this problem by only considering non-null/non-undefined values for <v-select>.

fix: error in filter options for null strings

---

src/components/ControlPanel.vue
src/components/dialogs/DialogSceneValue.vue

If you have a large number of nodes it is not easy to find the relevant ones in the selection list.
Therefore I suggest to sort them by display name (using `_name`).
Affected selections:
* groups: node and target selection
* scenes: node selection
In addition, the node selection in the scenes tab did not filter failed nodes, which has been changed for consistency too.

fix(ui): inconsistent, unsorted node selection

---

lib/ZwaveClient.js
package-lock.json
package.json

fix: better node initialization

---

app.js
config/app.js
docs/guide/env-vars.md
docs/guide/mqtt.md
docs/usage/reverse-proxy.md
lib/Gateway.js
lib/MqttClient.js
lib/ZwaveClient.js
lib/jsonStore.js
lib/logger.js
lib/utils.js
test/lib/logger.test.js

feat: env var STORE_DIR and renamed OZW_NETWORK_KEY to NETWORK_KEY

---

docs/getting-started/why.md

Some places is listed as zwavejs and other as zwave-js, so I changed all the one I found as zwavejs for uniformity.

docs: fix small typo why.md

---

docker/docker-compose.yml

added port expose for new zwave-js websocket server and annotations to help the new.

chore(docker): add zwave-js server port binding in docker-compose.yml

---

docs/usage/setup.md

The relative link was broken. It looks like absolute links were used elsewhere in the docs, so I went with that.

docs: fix homeassitant link in setup

---

src/components/Settings.vue

Issue #472 
Temp "fix"
I'm thinking the settings panel needs to be rearranged a little.
This setting for example should be enable to enable instead of enable to disable. 
Also, I'm thinking the settings should be:
- General
- Zwave
- Enable WS server. (instead of inside of Zwave) (show the relevant options if toggle on)
- Enable MQTT Gateway. (show the relevant options if if toggle on) (opposite behavior from current)
Seems like an easy change so if you like the idea I'll figure out how to do it and submit another PR.

fix(ui): settings labels

---

docs/guide/mqtt.md
lib/ZwaveClient.js
src/components/Confirm.vue
src/components/ControlPanel.vue
src/components/nodes-table/NodeDetails.vue
types/index.d.ts

fix: allow to set custom firmware target

---

docs/getting-started/quick-start.md

Fixed typo for typical copy/paste text

docs: fix typo in quick-start.md

---

lib/ZwaveClient.js

When non-zero target is specified, it does not get copied to a data member that is passed to the beginFirmwareUpdate method.  This fixes that so that when the user specifies a non-zero target, it will be passed along.  This was causing a failure related to [zwave JS issue 1761](https://github.com/zwave-js/node-zwave-js/issues/1761)

fix: firmware target not set correctly

---

app.js
lib/MqttClient.js
lib/ZwaveClient.js

fix: better app shutdown detection

---

docker/Dockerfile.contrib

Yarn timeout of 30000 (aka 30 seconds) seems to result in sporadic build failures with an RPC timeout.  Affected yarn package varies.  I was getting in 1 in 3 failures using github webhooks and saw it once locally.
I set to 300000 (aka 5 minutes) and this resulted in over 40 builds with github webhooks.  In the spirit of reliability is more important than speed i think we should make this change.  I haven't tried a shorter value to find where the cut off is between good and bad.  Githib build times with this flag varied between ~30 minutes and ~hour.

bug: updated yarn timeout to avoid sporadic build errors

---

lib/Gateway.js

This fixes the missing color channel 0 for Color Switch CC and avoids value clashes between all values and color 0 when https://github.com/zwave-js/node-zwave-js/pull/1782 is merged.

fix: propertyKey may be zero

---

docker/Dockerfile
docker/Dockerfile.contrib

dependabot changed all references to  to `node:erbium-buster-slim` to `node:15.9.0-alpine`.
This PR reverts those changes.,

bug: fixed dockerfile and dockerfile.contrib to use node:erbium-buster-slim

---

.github/workflows/docker-release.yml
.github/workflows/docker-test-amd64.yml
.github/workflows/docker-test-arm64.yml
.github/workflows/docker-test-armv6.yml
.github/workflows/docker-test-armv7.yml

The idea behind this is to improve docker builds speed by splitting actual dockerbuild workflow in 5 different workflows: 
- 4 workflows one for each arch for PR tests (no push to docker): linux/arm64,linux/amd64,linux/arm/v6,linux/arm/v7
- 1 workflow that runs on release created and on push to master that works like it is now builds all the images needed and push them to dockerhub

chore: improve docker builds

---

package-lock.json
package.json

This version introduces a new schema versioning system to support backwards compatibility

chore(deps): bump @zwave-js/server from 1.0.0 to 1.1.0

---

docker/README.md

chore: k8s deployment CR formatting

---

lib/ZwaveClient.js
src/components/ValueId.vue

fix(ui): allow manual entry on config values with states

---

lib/ZwaveClient.js

The accepted convention for representing manufacturer and product identifiers appears to use hexadecimal.

fix: show hex number along with the `unknown` strings

---

app.js
docs/usage/setup.md
lib/Gateway.js
src/components/Settings.vue
src/components/nodes-table/HomeAssistant.vue
types/index.d.ts

With this setting discovery payload will not be sent on startup but users will be able to send them manually from the UI. Useful when using mqtt discovery paired with zwavejs integration to discovery only some entities. Fixes #819

feat(hass): added `manual discovery` setting

---

lib/Gateway.js

Home assistant fixed a behaviour on MQTT Covers. we need to remove state_topic, as it breaks the use of MQTT Cover
Fixes #830

fix(hass): remove `state_topic` on covers for HA 2020.3.2

---

lib/Gateway.js

If spaces are used within the node name, the mqtt discovery topic contains spaces as well.
This is not supported by a lot of MQTT clients, like homeassistant.

fix: use prefixed node.id in mqtt discovery topic

---

src/App.vue

fix(ui): make version copyable from info box

---

lib/Gateway.js

fix: revert PR #920 "use prefixed node.id in mqtt discovery topic"

---

lib/ZwaveClient.js

fix: undefined propertyName in notifications

---

src/components/ControlPanel.vue

fix(ui): prevent sending removeFailed to sleeping nodes in broadcast

---

src/components/custom/ZwaveGraph.vue

fix(ui): use transparent background on zwave graph groups

---

app.js
src/apis/ConfigApis.js

Fixes https://github.com/hassio-addons/addon-zwavejs2mqtt/issues/4#issuecomment-819371878
/cc @frenck

fix: prevent 404 errors in store when using nginx

---

lib/Gateway.js

fix(hass): sending `true` to MultilevelSwitchCC doesn't restore old level

---

.github/workflows/docker-release.yml
.github/workflows/docker-test.yml

👋🏼 Hi @robertsLando here's a PR to publish the Docker image to Github container registry and keeps dockerhub.
The reason for this is Dockerhub has pretty serious rate limits (100 per 6 hours). Having and additional Docker registry would be awesome and it's so simple with GHCR.
This change requires a PAT being created and secrets in teh repo settings for:
- `GHCR_USERNAME`
- `GHCR_TOKEN`
After the image is pushed you will need to make the image public in the Github package.
Thanks for the consideration, hoping you find this useful.

feat(docker): push image to ghcr

---

lib/ZwaveClient.js
types/index.d.ts

fix: allow `sendCommand` to accept string command classes

---

docs/getting-started/quick-start.md

Add information about using the snap package under Rasbian/Debian as it requires some system modifications that is not common and cant be changed from the Snap-package.

docs: update quick-start

---

docs/guide/mqtt.md
lib/ZwaveClient.js
src/components/ControlPanel.vue
src/components/nodes-table/NodeDetails.vue
types/index.d.ts

feat: ping node

---

lib/ZwaveClient.js

It's now `zwavejs_%DATE%.log` after introducing log rotation

fix: change default zwavejs log file name

---

lib/ZwaveClient.js

fixes: https://github.com/zwave-js/zwavejs2mqtt/issues/1223
@robertsLando can I interest you in some TypeScript to avoid this kind of stuff? 😅

fix: put deviceConfigPriorityDir where it belongs

---

app.ts

expressjs is using static config, but we have option to restart plugins without restarting the whole service (when restarting zwave after applying settings). Plugin will fail (silently) to register expressjs handler after such restart.
Problem may be tested with the following plugin:
```
class TestPlugin {
constructor(ctx) {
this.zwave = ctx.zwave
this.mqtt = ctx.mqtt
this.logger = ctx.logger
this.app = ctx.app
var text = new Date().toString()
this.logger.info(`Starting at: ${text}`)
this.app.get('/test', function(req, res) {
res.send(`Started at: ${text}`)
})
}
async destroy() {
this.logger.info('Stopped')
}
}
module.exports = function(ctx) {
return new TestPlugin(ctx)
}
```
* Start zwavejs2mqgg, curl to `/test`.
* Go to settings page and click 'Save'
* curl to '/test' and you will see …

fix: plugins router must be recreated on restart

---

app.ts

cc @kvaster. I also tried to place history middleware right before error handlers but that's not working. I have placed the pluginsRouter before the history one as you suggested

fix: place plugins route before history middleware

---

docker/Dockerfile

Yarn add needs to be used for plugin installs, otherwise it will not
work.
by this addition we fix this issue

chore(docker): yarn fails to install plugins

---

hass/configurations.ts

This fixes a side-effect from the changes in zwave-js/zwavejs2mqtt/pull/290 that caused using the toggle to turn a dimmer on to make the light come on at full brightness instead of restoring the previous level (see discussion at end of #294). While there might be an argument for that as intentional behavior, this change also brings the behavior over MQTT in line with the behavior when using the direct ZwaveJS integration (where Zwave dimmers return to their previous brightness when the toggle is used).
The only caveat I can find in my testing is a very slight but noticeable delay on the brightness slider updating, because HA isn't sending a brightness so it doesn't preemptively move the slider.

fix(hass): make dimmers turn on to previous brightness

---

lib/Gateway.ts
lib/ZwaveClient.ts

Fixes #1367. When payload type is set to JSON or Zwave ValueId write requests (topics with `/set` suffix) can contain `options` oobject in payload and them will be used as options in `setValue` call

feat: add option to writeValue api

---

hass/devices.ts

I've got a couple of the GE 14314 with the older firmware (i.e. the 12600 product id). But figured while I was at it I should also add 12850 which should be newer variants per the [zwave alliance data](https://products.z-wavealliance.org/Search/Index?regionId=2&searchText=14314). You will see there are 3 variants registered as 14314. 2 of which share the `12600` (i.e. ` 0x3138` hex encoded) product id and 1 has `12850` (i.e. `0x3232` hex encoded).

fix: change the GE/Jasco 14314 to use the fan dimmer hass discovery

---

docs/guide/env-vars.md
hass/devices.ts
lib/MqttClient.ts

I added the option to configure the mqtt name using an env variable. 
I needed this in order to manage several pods in a kubernetes cluster.

feat: add `MQTT_NAME` env var

---

lib/ZwaveClient.ts

For some reason, the controller no longer exists after its event handler is invoked.
I don't know why this happens. It should not, but it does and it bombs sentry with errors.

fix: catch "controller not ready" error in statistics event handler

---

package.json
yarn.lock

No new features just yet, just reduces the load on our telemetry infrastructure

chore: bump zwave-js to 8.1.1

---

app.ts
docs/guide/mqtt.md
lib/SocketManager.ts
lib/ZwaveClient.ts
src/components/ControlPanel.vue
src/components/Settings.vue
src/components/dialogs/DialogAddRemove.vue
src/components/nodes-table/NodeDetails.vue
src/components/nodes-table/nodes-table.js
src/modules/ManagedItems.js
src/plugins/socket.js
src/store/mutations.js

- Added new ZwaveClient methods `grantSecurityClasses` `validateDSK` `abortInclusion`
- Changed signature of `startInclusion` and `replaceFailedNode` methods
- New socket events
- Added `securityKeys` object setting to Zwave settings (replaces the old `networkKey` setting, old settings are automatically updated to the new format so it's back compatible)
- Added node `security` property that shows the security class used by the node (S2, S0, None, ...)
- Completely refactored Add/Remove dialog to support new inclusion steps and replace failed nodes:
https://user-images.githubusercontent.com/11502495/130618833-ec2e13b1-38c0-4d1f-a959-ab70c1e0d990.mp4

feat: support for S2 inclusion

---

package.json
yarn.lock

This reverts commit 706343400b98c75aed43a9aebe93c0fd3ed9600a.
Fixes #1728

fix: icons are no longer displayed after css-loader major upgrade

---

app.ts

It will return a json like:
```js
{
z2m: <zwavejs2mqtt version>,
zwavejs: <zwavejs version>,
zwavejsServer: <zwavejs server version>,
}
```
Fixes #1701

feat: add `/version` api

---

package.json
yarn.lock

Changelog: https://github.com/zwave-js/zwave-js-server/releases/tag/1.10.7
Can we get a release pushed with this new server? We will require this version of the server on the next HA release

chore(deps): bump @zwave-js-server@1.10.7

---

.github/workflows/docker-release.yml

long time, no PRs (sorry, busy few months)
I wrote a blog post on what+why for this https://www.appvia.io/blog/tutorial-keyless-sign-and-verify-your-container-images :)

chore(docker): use cosign to sign the container images

---

.github/workflows/docker-release.yml
.github/workflows/docker-test.yml

caching is probably less relevant really for this now we're not waiting on ozw to compile, and with zwjs is changing so much, we probably never benefit from the cache, so you could remove this entirely but this might at least simplify the steps in the meantime

chore(docker): use in built docker gha caching for build

---

app.ts
docs/guide/env-vars.md

This PR allows a SSL cert and key to be defined by an environment variable. Fully tested on my end.

feat: allow SSL key to be specified via env var

---

docker/docker-compose.yml

typo: one colon too much in the mapping of the named volume.

chore(docker): fix typo in docker-compose.yml

---

.vscode/settings.json
lib/Gateway.ts
lib/MqttClient.ts
lib/ZwaveClient.ts
src/components/Settings.vue
src/lib/utils.js
src/store/mutations.js

BREAKING CHANGE: Some socket and zwave client events names and content have changed. This will not affect normal users but could cause some breaking changes on users using custom Plugins:
- `NODE_UPDATED` socket event now contains the entire node or the props that have changed
- `nodeInited` new zwave client event emitted when node is inited
- `valueWritten` event signature has changed: `valueWritten: (valueId: Z2MValueId, node: Z2MNode, value: unknown) => void`

feat: optimize socket events and mqtt disabled events

---

lib/Gateway.ts

Z-Wave mode mapping (hassModes array)
mode_map value for extended Z-Wave modes 
setpoint selection, if no mode-specific setpoints
Fixes #2059

fix(hass): thermostat mode mapping

---

docs/guide/mqtt.md
lib/ZwaveClient.ts
src/components/ControlPanel.vue

feat: use new `restoreNVM` API to restore NVM backups

---

.github/workflows/docker-release-test.yml

A new workflow has been created to create test releases with `test` tag every time there is a push to `test` branch

chore: add test branch release workflow

---

hass/configurations.ts

I believe this fixes https://github.com/zwave-js/zwavejs2mqtt/issues/1786
`barrier_state` needs a `value_template`, otherwise the `state_*` attributes won't work on JSON payloads.
In my HA logs I was seeing:
```
2022-01-07 13:29:14 WARNING (MainThread) [homeassistant.components.mqtt.cover] Payload is not supported (e.g. open, closed, opening, closing, stopped): {"time":1641576755633,"value":255}
```
I narrowed this down to my Nortek NGD00Z-4 Garage Door Controller.
Payloads coming from it look like this:
```
{"time":1641576755633,"value":255}
```
Here's the current MQTT Discovery Payload:
```
position_topic: zwave/Garage_Door_Opener/102/0/currentState
state_topic: zwave/Garage_Door_Opener/102/0/currentState
command_topic: zwave/Garage_Door_Opener/102/0/targetState/set
position_template: …
```

fix(hass): barrier State needs value_template

---

src/App.vue
src/components/ControlPanel.vue
src/components/Mesh.vue
src/components/Settings.vue
src/components/SmartStart.vue
src/components/Store.vue
src/components/custom/StatisticsCard.vue
src/components/dialogs/DialogAddRemove.vue
src/components/nodes-table/AssociationGroups.vue
src/components/nodes-table/ExpandedNode.vue
src/components/nodes-table/NodeDetails.vue
src/components/nodes-table/index.vue
src/store/mutations.js

I guys.
I'm using this piece of code every day via home assistant, and I love it !
However, I noticed minor possible enhancements that I propose to share with this PR.
Comments and remarks are welcome.
Here's what is modified :
Statistics panel now shows all possible stats grayscaled when empty, and blue / red colors are applied when a value is set.
This makes the panel size, and the stats positions predictable over time, whereas it does not visually take more place.
I think it is useful when someone is quickly searching for a specific stat.
Stats are also grouped by logical sections: `MESSAGES`, `COMMANDS`, `COMMUNICATION`.

feat(ui): flatten UI when elevation is not necessary (#2317) by @floutchito

---

src/App.vue

Dark mode was not initialized to the stored value at startup
Fixes https://github.com/zwave-js/zwavejs2mqtt/pull/2317#issuecomment-1076825090

fix(ui): initialize darkMode at startup

---

src/components/dialogs/DialogAddRemove.vue

This will pop a digit-first keyboard instead of a letter-first one.

fix(ui): hint to on-screen keyboards that DSK pin is numeric

---

lib/utils.ts

Even though `execSync` is wrapped in a try...catch it will still output error messages in docker console.
This will introduce a check for the git command in the shell, if it doesn't exist, then `exit 0` else run the git command. This avoids throwing and catching errors and keeps the logs clean.

fix: avoid showing git error on startup

---

docs/troubleshooting/generating-logs.md

I've just added the first `"silly"` level logs to the driver, but they are generally not necessary and would clutter the logs.
We should recommend users to use `"debug"` instead.

docs: recommend loglevel "debug" for Z-Wave logs

---

docker/Dockerfile.contrib

This PR does a few things:
1. make Dockerfile.contrib compatible with zwave-js 10 and replace the hacky solution for packing the local build with a better one
2. reduce the number of layers by grouping RUN commands
3. fix a crash caused by a missing snippets folder

fix(docker): use zwave-js's new pack utility, optimize layers, copy snippets

---

docs/homeassistant/homeassistant-official.md

I had some troubles configuring the zwave-js-ui addon in HA, as I was consistently confused by the documentation which led me in circles. I was focusing on this doc though, so I believe that by making this more explicit, future users can be helped. Through slack, I also found that the "actual" docs are over on HA - where I believed that zwave-js(-ui) wasn't so well included in those docs.. The HA docs are better for actual setup, so I've made sure the step-by-step ends over there.

docs: rework the docs on HA Zwave-js integration to be more explicit

---

.github/workflows/docker-release.yml
docs/getting-started/docker.md

On release this adds tags `${major}` as well as `${major}.${minor}` to the container images.
This is quite common practice and allows users to follow minor or major releases instead of only `latest` _(typically not recommended)_ or specific patch versions, requiring to constantly monitor for new patches releases.
Any feedback is welcome. :)

chore(docker): add tags for `major` and `minor` version to container images

---

src/components/ControlPanel.vue

The word `update` was previously spelled `udpate`. This was apparent on the dialog popup when navigating within the UI to a node, then Advanced, and after selecting "Begin" under "Firmware Update" of the "Advanced" popup.

fix(ui): typo in fw update dialog title

---

lib/Gateway.ts
lib/ZwaveClient.ts

fix(mqtt): always send zwaveNode to node `event` as first arg

---

docs/homeassistant/accessing-lovelace.md

The URL only had one forward slash in it, and when I added this to the version of homeassistant I just installed, it had an additional "views" stanza in it so I included that full yaml.

docs: correcting typo on URL and updating to newer dashboard yaml

---

.github/workflows/ci.yml
.github/workflows/docker-release-test.yml
.github/workflows/docker-release.yml
.github/workflows/docker-test.yml
.github/workflows/release-it.yml
.github/workflows/update-dep.yml
.github/workflows/zwave-js-bot_comment.yml

Changes:
- Fix actions for set-output and save-state deprecations.
- update `actions/github-script` to new version from v3 to v6 (takes care of node v12 issue)
- update `actions/node-setup` from v3.4.1 to v3.6.0 (takes care of save-state issues)

chore: fix deprecation on GH actions

---

.github/workflows/docker-release.yml
src/components/nodes-table/nodes-table.js

This could fix the bug that for some reason stucks the release workflow and requires me to retrigger it

chore: prevent dups runs on releases

---

lib/Constants.ts

Add missing state_class attribute required for HA and energy statistics/dashboard
Fixes #2943

fix(discovery): add `state_class` to kwh sensors

---

lib/logger.ts

To enable monitoring via fail2ban as discussed in https://github.com/zwave-js/zwave-js-ui/discussions/2933. Mirrors similar code addressing same feature for the zwave logs as per https://github.com/zwave-js/node-zwave-js/issues/3796.

fix: create symlink to current UI logfile

---

package.json
yarn.lock

Update zwave-js-server to version 1.26.0
@robertsLando can we release for this?

feat: bump zwave-js-server@1.26.0

---

.github/workflows/ci.yml
.github/workflows/update-dep.yml
.github/workflows/zwave-js-bot_comment.yml

node 14 LTS security patches end in [2 months](https://endoflife.date/nodejs), so getting ahead of this and removing the references for node 14 and see what CI things it breaks

chore(deps): remove support for node 14

---

lib/MqttClient.ts

I setup [sonarcloud](https://sonarcloud.io/summary/overall?id=lightswitch05_zwave-js-ui) on my fork, and this was reported as a bug. I don't use the MQTT gateway on my local setup, so I'm not sure what type of testing is required, but it seems like a pretty obvious bug.

fix: toSubscribe being set to bool instead of map

---

kubernetes/deployment.yaml
kubernetes/service.yaml

HomeAssistant needs to use the websocket APIs to operate, but the websocket port is not exposed in the current definitions. By declaring the port, one can write an `Ingress` if desired to expose the websocket server on port 80/443 like so:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: zwave-ws
annotations:
cert-manager.io/cluster-issuer: "letsencrypt"
spec:
tls:
- hosts:
- zwave-ws.example.com
secretName: tls-zwave-ws-ingress-http
rules:
- host: zwave-ws.example.com
http:
paths:
- path: /
pathType: Prefix
backend:
service:
name: zwave
port:
name: websocket
```

feat: websocket support to kubernetes configs

---

package.json
yarn.lock

as usual, would love a release for this so that we can include support for 10.11 and 10.12 features

feat: bump zwave-js-server@1.27.0

---

lib/Constants.ts
package.sh
test/lib/Constants.test.ts

There are several sensor types that do not currently report a property of "state_class": "measurement" which means home-assistant does not have the ability to show them in a statistics graph. This causes issues for certain types of UI cards as they are unable to display any data. 
Documentation for the values is here: 
https://developers.home-assistant.io/docs/core/entity/sensor/#available-state-classes
I have run `yarn test` and `yarn lint` successfully. I have also updated the matching test. 
Additionally when trying to run `yarn pkg` I ran into two issues.
1. `egrep` deprecation (migrated to `grep -E` per: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/grep.html)
1. `arch` command binary not available (migrated to `uname -m` per: https://linux.die.net/man/1/arch)
Testable …

feat: added state_class: measurement to appropriate sensors

---

app.ts

there was an error in the `isAuthenticated` function which also sent the `res.json(...)` error response after calling `next()` without returning from the function
this will fix #3133

fix: authentication flow for JWT tokens

---

lib/ZwaveClient.ts
src/components/nodes-table/SmartView.vue
src/components/nodes-table/nodes-table.js
src/lib/utils.js

For fibaro thermostat we may have endpoint 1 and endpoint 2 for batteries. In such case battery level for endpoint 0 will be also shown. And it will be shown as 'null' value.

fix(ui): filter battery null values

---

src/mixins/InstancesMixin.js

Fix a minor typo in the toast messages for ping and heal actions. This should read "successful", not "successfull". Thanks for this amazing project!

fix: minor typo in ping and heal messages

---

package.json
yarn.lock

- https://github.com/zwave-js/node-zwave-js/releases/tag/v11.7.0
- https://github.com/zwave-js/node-zwave-js/releases/tag/v11.8.0

chore: bump zwave-js to 11.8

---

package.json
yarn.lock

https://github.com/zwave-js/zwave-js-server/releases/tag/1.30.0

feat: bump zwave-js@11.8 and @zwave-js/server to 1.30.0

---

src/components/nodes-table/NodeDetails.vue

The message regarding the typical controller powerlevel settings is not really accurate anymore. Both Zooz and Aeotec use different values. It probably only applies to the UZB7 developer reference board and the US region, but even SiLabs has never provided correct numbers. It's better to just remove these as it causes confusion when using other models of controllers.

fix: remove controller default powerlevel message

---

src/components/custom/ZwaveGraph.vue

change the legend text color to match the legend icon's color.
Before (dark): 
Before (light):
After (dark):
After (light):

fix(graph): match text color with icon color on ZWave Graph legend

---

package.json
yarn.lock

Changelog: https://github.com/zwave-js/zwave-js-server/releases/tag/1.32.0

chore: bump @zwave-js/server to 1.32.0

---

package.json
yarn.lock

@robertsLando 1.32.0 breaks HA for people not on the beta. Can we merge and release this package update?

fix: bump @zwave-js/server to 1.32.1

---

package.json
yarn.lock

Update zwave-js to version 12.0.3
Sounds like we need a new release after this

feat: bump zwave-js@12.0.3

---

app.ts
lib/Gateway.ts
package.json
src/App.vue
src/apis/ConfigApis.js
src/components/Confirm.vue
src/stores/base.js
src/views/Settings.vue
yarn.lock

feat: show releases changelog on login

---

docs/getting-started/docker.md

Correct spelling of semantic on line 24.

docs: update docker.md

---

src/views/Debug.vue

fix(ui): formatting in debug window

---

src/components/nodes-table/OTAUpdates.vue

fix(ui): disable ota updates while upgrading

---

.env.app.example
app.ts
bin/www.ts
config/app.ts
docs/guide/env-vars.md
src/views/Settings.vue

fix: set default host to undefined

---

esbuild-register.js
nodemon.json
vite.config.js

chore: fix custom build with zwave-js

---

api/config/app.ts
api/lib/ZwaveClient.ts

Currently, if `ZWAVEJS_LOGS_DIR` is setted, the `STORE_DIR/logs` directory continues to be created without any content being saved in it.

fix: don't create `STORE_DIR/logs` if `ZWAVEJS_LOGS_DIR` is setted

---

docker/Dockerfile

A Dockerfile RUN command has a shell syntax error:
```text
[2/3] STEP 4/13: RUN [ -d 'node_modules' ] && echo "Skipping install" || npm install $([ -d 'dist'] && echo '--omit=dev' || echo '')
sh: missing ]
```
The `[` command requires spaces around the expression.

fix(docker): shell syntax error

---

api/lib/ZwaveClient.ts

Fixes #3461.
If the driver has not been created, and some Z-Wave client API is called, an exception is thrown:
```text
2023-12-02 12:04:48.586 INFO Z-WAVE: Calling api getProvisioningEntries with args: [ [length]: 0 ]
2023-12-02 12:04:48.586 ERROR APP: Unhandled Rejection, reason: TypeError: Cannot read properties of undefined (reading 'isInBootloader')
TypeError: Cannot read properties of undefined (reading 'isInBootloader')
at ZwaveClient.callApi (/home/keith/src/zwave-js-ui/src/api/lib/ZwaveClient.ts:2710:41)
at Socket.<anonymous> (/home/keith/src/zwave-js-ui/src/api/app.ts:518:41)
at Socket.emit (node:events:529:35)
at Socket.emitUntyped (/home/keith/src/zwave-js-ui/src/node_modules/socket.io/dist/typed-events.js:69:22)
at /home/keith/src/zwave-js-ui/src/node_modules/socket.io/dist/soc …
```

fix: check for undefined driver

---

.gitignore
api/lib/ZwaveClient.ts
api/lib/utils.ts
esbuild.js
package.json

feat: create esbuild bundle for embedded devices

---

src/views/Settings.vue

Correctly align `preferred scales` with `log enabled` on settings -> Zwave.
Currently:
After:

fix(ui): preferred scales alignment

---

api/lib/Gateway.ts
api/lib/MqttClient.ts

Require the client to be connected (LWT will set to false when MQTT connection is lost because the process goes down), the driver to be ready, and the individual node to be online

feat(discovery): add support for availability topics

---

api/hass/configurations.ts
api/lib/Gateway.ts
api/lib/ZwaveClient.ts

but disable them by default. this gives you the option of creating automations around them if you desire, or ignoring them if you don't need them

feat: expose configuration properties via HASS discovery

---

api/lib/Gateway.ts

* don't expose writable values as read-only scenes
* give HA a hint when values are numbers and not strings

fix(discovery): improve MQTT discovery for scene CC

---

src/components/nodes-table/HomeAssistant.vue

feat(ui): allow to toggle persistent/discovery fields from HA discovery table

---

api/lib/ZwaveClient.ts

fix: node name and location change not catched on value added

---

api/lib/logger.ts
package-lock.json
package.json
test/lib/logger.test.ts

fix: create custom logs cleanup function

---

api/lib/ZwaveClient.ts

fix: better message in case association is not allowed

---

src/lib/utils.js

This PR is intended to update the colors of the protocol icons to those of the [Material design palette offered by Vuetify](https://vuetifyjs.com/en/styles/colors/#material-colors). This matches the color palette of the other columns in the node table.
Considerations:
* In the spirit of an easily digestible PR, I am not addressing non-Material colors elsewhere in the ZWJS UI
* I tried using `colors.indigo.base` for `Protocols.ZWave`, but the contrast between ZWave and ZWaveLongRange wasn't great. There isn't a good color in the material design palette that's close to the outdated `rgb(0, 0, 255)` color -- perhaps one of the indigo/blue accent colors would better match the original author's intention.
* There's no requirement to adhere to the original author's intention -- it's not like …

fix(ui): use vuetify's material design palette colors for protocol color

---

src/components/nodes-table/ColumnFilter.vue
src/components/nodes-table/index.vue

Adjusts the headers in the nodes-table to not break lines.
Adjust minor css of headers to make it pleasant
- Before:
- <img width="1329" alt="image" src="https://github.com/zwave-js/zwave-js-ui/assets/1888323/2cafc663-252e-4c2b-bbaa-914fa3084179">
- After:
- <img width="1329" alt="image" src="https://github.com/zwave-js/zwave-js-ui/assets/1888323/8cde79d6-9857-4c73-9ff5-4a2276ae8f12">

fix(ui): nodes table header from breaking line

---

api/lib/ZnifferManager.ts

fix: set up events before calling `Zniffer.init()`

---

api/lib/ZwaveClient.ts

EU has region 0, so it was never passed to the driver.

fix: setting default region to EU

---

api/lib/ZwaveClient.ts

This broke some driver-internal functionality that relied on event listeners it had previously added.

fix: do not remove controller event listeners

---

api/lib/utils.ts
docs/guide/env-vars.md

Add environment variables to override the long range security keys.
- `KEY_LR_S2_Authenticated`
- `KEY_LR_S2_AccessControl`
Ideally, this shouldn't any features outside of configuration of the long range security keys on startup.
Seems to work on my local setup now. 🎉 
Fixes #3765

feat(env): add Long Range key overrides from env

---

api/lib/ZwaveClient.ts
src/components/nodes-table/NodeDetails.vue

Ref: https://github.com/zwave-js/node-zwave-js/pull/6957

feat: show supported controller rf regions

---

nodemon.json

Since the switch back to `npm` this no longer works

chore: do not watch local zwave-js repo

---

src/apis/ConfigApis.js

Throw exception when `401` returned from `/auth-enabled` to trigger page reload. This is needed for  http basic auth to work properly.
I run zwave-js-ui behind basic http auth and get  "Unexpected end of JSON input" error after browser restart:
This happens when `401` status is returned since Chrome keeps auth only until browser restart.
Typically Chrome would display the auth popup in this case  but turns out it doesn't work requests made by service workers:  
https://issues.chromium.org/issues/40474438
This is essentially the same issue as  #3427 
FWIW Without this PR, it can be "fixed" with the following Caddy config (send `302` when `Authorization` header is missing)
```
(auth) {
basicauth {
...
}
}
zwave.mydomain.com {
@auth_check {
path /api/auth-enabled
header !Authorization
} …
```

fix(ui): trigger page reload on 401 (fix basic auth)

---

api/lib/ZwaveClient.ts

feat: use `inclusion state changed` event

---

src/assets/css/main.css
src/views/Settings.vue

- Sticky buttons
- Disable save when no changes detected
- Warn before leaving ui if there are unsaved settings
Fixes #3870

feat(ui): settings ui improvements

---

api/lib/Gateway.ts
api/lib/ZwaveClient.ts

fix(discovery): use valueId endpoint device class for multilevel switch CC discovery

---

src/components/custom/NodePanel.vue

Per [this Discord discussion](https://discord.com/channels/330944238910963714/332357267364249621/1284184575534305382) and a search of "NLWR" in the Z-Wave specifications, "Next Last" is the wrong name for the dashed line.

fix(ui): correct legend wrt nlwr

---

docs/development/intro.md
vite.config.mjs

`SERVER_URL=https://192.168.1.x:8123/api/hassio_ingress/abcdefg INGRESS_TOKEN=123456789  npm run dev`
I needed a way to connect my local development frontend to the remote zwave-js-ui backend. Since the HASSIO docker container doesn't expose the port to the host the easiest way around it is via [Hass.io Ingress](https://www.home-assistant.io/blog/2019/04/15/hassio-ingress/). Unfortunately that needs cookie authentication, which can be easily injected via Vite's built-in proxy. This PR adds an `INGRESS_TOKEN` env variable where you can specify the token and it will take care of injecting the cookie for each API request. Use Chrome/Firefox DevTools to figure out what's the correct Ingress `SERVER_URL` and `INGRESS_TOKEN`.

feat: add INGRESS_TOKEN env variable to set the ingress session cookie

---

api/hass/configurations.ts
api/lib/Gateway.ts

feat(discovery): add `supported_color_modes` to lights

---

api/lib/ZwaveClient.ts

feat: listen for `node info received` event

---

src/lib/items.js
src/views/Settings.vue

This PR groups the Z-Wave settings panel a bit more logically, adds subheadings and explains some settings a bit better. Also it is no longer possible to choose "Unknown" and "Default (EU)" as default regions, since they are not a valid setting.

feat(ui): re-order Z-Wave settings, prevent setting invalid regions

---

api/lib/ZwaveClient.ts
src/mixins/InstancesMixin.js

Fixes https://github.com/zwave-js/zwave-js-ui/issues/3983

feat: allow to upload firmware in zip files

---

esbuild-import-meta-url-shim.js
esbuild.js

fixes the new error "The argument 'filename' must be ..." reported in https://github.com/zwave-js/zwave-js-ui/issues/3995
fixes: #3995

fix: replace `import.meta.url` with CJS shim

---

.github/workflows/test_install_arm64.yml
package-lock.json
package.json

Fixes #4007. Ref: https://github.com/rollup/rollup/issues/5194#issuecomment-1833271025

fix: rollup not working on arm

---

src/components/nodes-table/NodeDetails.vue

Correcting a grammatical mishap and fixing a visual glitch where two texts are squished together

fix(ui): typo on NodeDetails.vue

---

api/config/app.ts
api/lib/ZwaveClient.ts
docker/Dockerfile
docker/Dockerfile.contrib
docker/Dockerfile.debian
docker/docker-compose.yml
docs/getting-started/docker.md
docs/getting-started/other-methods.md
docs/guide/env-vars.md

This will prevent issues when not setting this env var causing `Writing the device index to disk failed: ENOENT: no such file or directory` on pkg
Ref #4053 #4003

feat: add default value for external Z-Wave JS config database path

---

src/lib/utils.js
src/views/Zniffer.vue

fix(ui): correctly display CRC errors on zniffer

---

src/components/dialogs/DialogLinkReliability.vue

Whenever I use this, I find myself setting the iterations to 100, so let's make it the default.

fix(ui): set default iterations for link reliability check to 100

---

docs/guide/healthcheck.md

Fix unclosed string in curl healthcheck documentation.

docs: typo on healthcheck.md curl command

---

api/lib/ZwaveClient.ts
src/components/nodes-table/NodeDetails.vue
src/lib/items.js
src/stores/base.js
src/views/Settings.vue

This PR adds support for changing the maximum powerlevel used by the LR dynamic power algorithm:
It also adds corresponding default settings in the settings tab.

feat: support changing max. LR powerlevel

---

api/lib/ZnifferManager.ts
api/lib/ZwaveClient.ts
api/lib/logger.ts
api/lib/utils.ts
package-lock.json
package.json
src/components/nodes-table/ExpandedNode.vue

BREAKING CHANGE: Drop support for Node.js < 20.0.0

feat!: bump zwave-js@15 and fix breaking changes

---

api/lib/PkgFsBindings.ts
api/lib/ZwaveClient.ts

As it turns out, Z-Wave JS would always look for the config directory on `C:\` due to how the current filename is set inside pkg. `path.resolve` on the other hand takes the current process directory into account, which might be on a different drive.
fixes: https://github.com/zwave-js/zwave-js-ui/issues/4183

fix: config path resolution inside pkg on Windows

---

api/lib/SocketEvents.ts
api/lib/ZwaveClient.ts
src/App.vue
src/lib/SocketEvents.js

Fixes #4194
BREAKING CHANGE: Starting from z-wave-js@15 OTW firmware update has been moved from controller to driver. Following this the MQTT event has been moved from `controller` `driver` and the payload will not be the entire controller node but only `progress` updates. This will only affect users implementing custom logics based on MQTT events.

fix!: add OTW firmware update event handling

---

package-lock.json
package.json
src/App.vue
src/components/Confirm.vue
src/components/custom/BgRssiChart.vue
src/components/custom/NodePanel.vue
src/components/custom/ZwaveGraph.vue
src/components/dialogs/DialogAssociation.vue
src/components/dialogs/DialogHealthCheck.vue
src/components/dialogs/DialogNodesManager.vue
src/components/nodes-table/AssociationGroups.vue
src/components/nodes-table/ExpandedNode.vue
src/components/nodes-table/NodeDetails.vue
src/components/nodes-table/NodeScheduler.vue
src/lib/items.js
src/lib/utils.js
src/views/SmartStart.vue
src/views/Zniffer.vue
vite.config.mjs

I'm planning to eliminate those entrypoints in the next major release. They are no longer necessary, since `zwave-js` and all its submodules are browser-compatible now.

refactor: eliminate usage of zwave-js's `/safe` entrypoints

---

api/lib/ZwaveClient.ts
package-lock.json
package.json

As of Z-Wave JS 15.3.0, receiving the `driver ready` event always implies a new controller instance, therefore old event handlers no longer exist. This PR makes the necessary changes.

feat: update zwave-js to 15.3.0, always add event handlers after `driver ready` event

---

src/App.vue

While not necessarily incorrect when expanded (the zwave-js user interface), "the ZUI" sounds poorly translated, and if ZUI is considered as a proper noun (actually expanding to Z-Wave JS UI), then the existing wording is grammatically incorrect (think "Are you sure you want to restart the Windows?").

fix(ui): typo in restart prompt

---

src/App.vue
src/components/custom/ColorScheme.vue
src/lib/colorScheme.js
src/stores/base.js
src/views/Login.vue
src/views/Settings.vue

We migrate from only supporting an explicit dark or light color scheme to also supporting whatever the current system preference is for the color scheme.
This allows folks to change their color scheme at the operating system level (whether they do it automatically or manually) and have that setting be reflected in Z-Wave JS UI. This also means that different device preferences should follow what the device has configured (e.g. a desktop might always be in dark mode, while a mobile device changes based on the time of day).
This is my first time contributing to `zwave-js-ui`, and I have limited experience with Vue. So apologies if I've done something wrong, or a bit off. Let me know if you have any suggestions/alternatives to the implementation.
Fixes …

feat(ui): support system preference color scheme

---

api/config/store.ts
src/lib/items.js
src/stores/base.js
src/views/Settings.vue

This is the first step to help users with configuring controllers for their region a bit easier than right now.
The RF region setting is now mandatory, so there are no surprises when switching controllers or setting up a new one that defaults to a different region.
Auto-powerlevel is now enabled by default, because nobody should have to deal with powerlevels anyways.

feat: make RF region setting mandatory, enable auto-powerlevel by default

---

src/components/custom/FirmwareUpdates.vue
src/components/nodes-table/OTAUpdates.vue

This is a followup to #4277 and replaces the region selector on the OTA page with a hint to configure the region in the settings.
When the current controller region is not known, the region from the settings is now used instead.
Unfortunately, I can't test that as I don't have a controller that does not support changing the region.

feat: use default RF region from settings for OTA update check

---

api/lib/ZnifferManager.ts
src/views/Zniffer.vue

Unlike NVM backups, Zniffer captures were not automatically downloaded. This PR changes that.

feat: download Zniffer capture after saving

---

src/views/Mesh.vue

Ref https://github.com/zwave-js/zwave-js/issues/8168

fix(ui): remove useless refresh neighbors call when opening mesh graph
