hass/devices.js
I suspect this may be necessary for other thermostats as well, but i have no way to test the other thermostats
=> fix topics for 2gig thermostats

docker/Dockerfile.contrib, docker/README.md
Based on the idea and work by @roflmao by #41.
This is an alternative solution that gives us both variants in a single Dockerfile.
Also added short sha to package versions.
=> Dockerfile with optional remote branch support from @roflmao

lib/Gateway.js
A typo, causes no subscription topics to be created in MQTT. this fixes the issue
=> try to fix undefined variable, due to one mising 'e'

src/components/Settings.vue
=> fix: network key generation #80

app.js
=> fix: Startup error in setupLogging()

lib/ZwaveClient.js, src/components/ControlPanel.vue
=> feat(ui): group values by command classes

app.js, lib/ZwaveClient.js, src/components/ControlPanel.vue, src/components/ValueId.vue
=> fix: read only list values in UI and better logging

app.js, lib/ZwaveClient.js, lib/logger.js
=> fix: broken logs and print stack if present

lib/Gateway.js, lib/ZwaveClient.js
Some missing comments been added on fix-109
=> Add comments for fix-109

hass/configurations.js, lib/Gateway.js
Low battery level is a binary sensor, but it is discovered through multilevel/sensors
Added some small changes, which can support cases like this in the future
=> Add support for Battery isLow binary sensor

src/store/mutations.js
=> fix: defaults settings values

app.js
=> fix: prevent empty node object to break import

src/components/Mesh.vue
=> fix: ensure target node exist when creating links

.github/bot-scripts/authorizedUsers.js, .github/bot-scripts/fix-lint-check.js, .github/bot-scripts/fix-lint-feedback.js, .github/bot-scripts/index.js, .github/bot-scripts/types.d.ts, .github/workflows/zwave-js-bot.yml, .prettierignore
=> chore: zwave-js bot

docs/guide/homeassistant.md
Follow-up to #205 
A user asked for additional detail regarding the lovelace change.
=> [feat] Add (more) directions to access the UI from within HA 

src/components/Settings.vue
=> feat: allow `/` in mqtt prefix #213

docs/usage/setup.md, lib/Gateway.js, src/components/Settings.vue
=> fix: entity names with empty location

.github/zwave-js-assistant.yml
@robertsLando The next app version is configurable, so you'll need this :)
=> chore: add config file for zwave-js-assistant app

lib/Gateway.js
Hass topics, are not respacting the ignoreLoc setting in config. Add support for this.
=> fix: Add Ignore location for hass topics

hass/configurations.js, lib/Gateway.js, src/components/ValueId.vue
=> feat: ui and hass discovery rgb valueId support

docs/guide/mqtt.md, lib/ZwaveClient.js
Fixes #260
@LordMike Check this out :)
=> docs: list allowed apis

.github/workflows/dockerbuild.yml, docker/Dockerfile
=> chore(docker): docker labels opencontainers v2

docker/Dockerfile.contrib
Improve the documentation, in response to #261
=> feat(docker): Improve documentation by linking to the readme

lib/Gateway.js, lib/ZwaveClient.js, src/components/ValueId.vue
Fixes #269 
@LordMike could you try this?
=> fix: hexColor parsing

docs/guide/mqtt.md, lib/ZwaveClient.js, src/components/ControlPanel.vue
Needs https://github.com/zwave-js/node-zwave-js/pull/1444
@ahochsteger
=> feat: markNodeAsFailed api

lib/Gateway.js
=> fix: add `origin` payload to api response payload

docs/guide/mqtt.md, lib/ZwaveClient.js, src/components/ControlPanel.vue
Ref 
https://github.com/zwave-js/node-zwave-js/pull/1456
https://github.com/zwave-js/node-zwave-js/pull/1444#issuecomment-763699022
=> fix: remove markNodeAsFailed api

build/webpack.base.conf.js
ref: https://github.com/webpack/webpack-dev-server/issues/2758
=> chore: fix webpack HMR

docs/guide/homeassistant.md
Change currentVaue to targetValue in the fan template like changed in:
https://github.com/zwave-js/zwavejs2mqtt/commit/0d0fbd678070dc2e979a809363815628b5a8a5d8
=> fix(hass): change currentValue to targetValue in the fan template docs

lib/Gateway.js, lib/ZwaveClient.js
=> fix: gateway values not working

docs/guide/homeassistant.md
Replaced Dashbaord with Dashboard
=> docs: typo home assistant docs

docs/usage/setup.md
I'm sorry I made so many PRs, I don't know how to have all of them in one but I'll figure out before I fix more typos.
=> docs: fix small typo setup.md

src/App.vue, src/components/ControlPanel.vue, src/components/Debug.vue, src/components/Mesh.vue, src/components/Scenes.vue, src/components/Settings.vue, src/components/Store.vue, src/components/nodes-table/AssociationGroups.vue, src/components/nodes-table/ExpandedNode.vue, src/components/nodes-table/NodeDetails.vue, src/router/index.js, src/store/mutations.js
@ahochsteger  in this pr I have moved node to store so we can access them easily from all tabs
=> feat(ui): move scenes and debug to side menu

.github/bot-scripts/renameCommitCheck.js, app.js, lib/ZwaveClient.js, package-lock.json, package.json, src/modules/ColumnFilterHelper.js
=> fix: rate limit store requests and sanitize path

lib/MqttClient.js
=> fix: safer subscribe

lib/Gateway.js, lib/MqttClient.js, lib/ZwaveClient.js, package-lock.json, package.json, types/index.d.ts
=> chore: define basic types

lib/ZwaveClient.js
=> fix: unknown manufacturer

docs/guide/homeassistant.md
Add example to execute scene from home assistant
=> docs: manual create entities on hass

docs/guide/mqtt.md
=> docs: fix send command example

docs/guide/mqtt.md
Add example for execute scene via mqtt
=> docs: Update mqtt.md

docs/usage/setup.md
Organized things so the docs matches the current order of the zjs2m settings, added a couple missing settings in zjs2m to the docs and removed a couple that I didn't see in zjs2m.
=> docs: changes to setup.md

lib/Gateway.js
=> fix: ignore stateless valueId updates if from cache

src/components/ControlPanel.vue
=> fix(ui): better ui add/remove dialog feedback

lib/ZwaveClient.js
cc @marcus-j-davies I saw that for some reason this was removed after the switch to zwavejs.
=> feat: custom plugins loader

docs/usage/setup.md, src/components/Settings.vue
Changed "applyed" to "applied" in two places.
=> docs: Fixing a typo I noticed

app.js
=> fix: `/health` return 200 if mqtt is disabled

lib/Gateway.js
=> fix: add node id to node status payload

lib/Gateway.js, src/components/dialogs/DialogGatewayValue.vue
=> feat: allow to specify custom qos and retain

src/components/nodes-table/index.vue
=> fix(ui): no secure nodes shown as secure

docs/guide/homeassistant.md
Just a few typos, nothing important.
=> docs: fix typos in homeassistant.md

app.js, config/index.js, src/components/Store.vue
=> fix: wrong filename when downloading file

src/components/custom/ZwaveGraph.vue
=> fix(ui): battery powered devices shown as main

docker/Dockerfile.contrib
=> chore(docker): fix broken Dockerfile.contrib

package.sh
=> chore: fix package script

docker/Dockerfile
=> chore(docker): add openssl

.github/ISSUE_TEMPLATE/hass_discovery.md
=> chore: create hass discovery issue template

app.js, lib/Gateway.js, lib/SocketManager.js, src/components/ValueId.vue, src/components/nodes-table/ExpandedNode.vue, src/components/nodes-table/NodeDetails.vue, src/plugins/socket.js, types/index.d.ts
=> feat(ui): update topics and clear retained functions

hass/devices.js, lib/Gateway.js
This PR fixes climate thermostats (like Danfoss LC-13).
Fixes #607
=> fix(hass): improved climates discovery

hass/devices.js, src/components/nodes-table/AssociationGroups.vue
Updated discovery to use changes found in [ZwaveJS #1782](https://github.com/zwave-js/node-zwave-js/pull/1782)
Fully working and tested on my box™
=> fix(hass): inovelli lzw42 multi color bulb discovery update

lib/Gateway.js, lib/ZwaveClient.js, types/index.d.ts
=> fix: use node `available` in node status

app.js
=> fix: bug when importing nodes.json

src/assets/css/my-progress.css, src/components/Store.vue
=> fix(ui): show scrollbars

lib/ZwaveClient.js
=> fix: assume controller always as listening

lib/ZwaveClient.js, lib/utils.js, src/components/ValueId.vue
=> fix: read/parse buffers as hex strings

lib/ZwaveClient.js, src/components/ValueId.vue
=> fix(ui): add missing type buffer

docker/README.md
Minor change, please let me know if you would like me to add or change anything.
=> docs: updates to docker readme

lib/Gateway.js, lib/ZwaveClient.js, types/index.d.ts
=> fix: prevent reset poll timers on node status updates

src/App.vue, src/router/index.js
=> fix(ui): redirects to main when auth is disabled

lib/ZwaveClient.js, src/components/custom/ZwaveGraph.vue, types/index.d.ts
Fixes #862. Added `isControllerNode` prop to nodes
=> fix(ui): zwave graph when controller id != 1

src/components/nodes-table/ExpandedNode.vue
=> fix(ui): disable swipe on node tabs

src/components/Confirm.vue, src/components/ControlPanel.vue
=> fix(ui): allow manual entry of nodeid

src/components/nodes-table/ExpandedNode.vue
=> fix(ui): restore node debug info tab

src/components/nodes-table/NodeDetails.vue
=> fix: allow spaces in name and location

lib/ZwaveClient.js, src/App.vue, src/components/ControlPanel.vue, src/components/dialogs/DialogAdvanced.vue, src/components/nodes-table/NodeDetails.vue, src/components/nodes-table/index.vue, src/components/nodes-table/nodes-table.js
=> feat(ui): improved control panel

src/components/Settings.vue
=> fix(ui): correctly show `Include Node Info`

src/modules/ManagedItems.js
Fixes #940 caused by localstorage inconsistence after upgrading to 3.0.0
=> fix(ui): control panel table not rendered

lib/ZwaveClient.js
=> fix: prevent stopInclusion/Exclusion to throw

lib/ZwaveClient.js
=> fix: correctly show heal process complete

lib/Gateway.js, lib/utils.js
Related to #920 
cc @blhoward2 @tmaroschik let me know your feedback on this please
=> fix: better sanitize topics

src/components/custom/ZwaveGraph.vue
=> fix(ui): check if node is routing

lib/utils.js
=> fix: allow accent chars in topics

app.js, lib/ZwaveClient.js, package-lock.json, package.json, src/App.vue, src/apis/ConfigApis.js, src/components/Confirm.vue, src/components/Settings.vue, src/store/mutations.js, types/index.d.ts
=> feat: make usage statistics opt-in

lib/ZwaveClient.js
=> fix: this.stopExclusion is undefined

src/components/custom/ZwaveGraph.vue
=> fix(ui): assume controller always forwards in mesh graph

src/components/custom/ZwaveGraph.vue
=> fix(ui-mesh): better labels color based on current theme

src/components/nodes-table/NodeDetails.vue
=> feat(ui): refresh CC values

lib/ZwaveClient.js
=> fix: notification event not publiished to mqtt

lib/ZwaveClient.js
=> fix: manually add missing values on updates

lib/ZwaveClient.js, src/components/Confirm.vue, src/components/ControlPanel.vue
=> feat: allow to send a custom function to driver

lib/ZwaveClient.js, src/components/ControlPanel.vue, src/components/ValueId.vue, src/components/nodes-table/NodeDetails.vue, types/index.d.ts
=> feat: allow to send custom Config CC get/set commands

lib/ZwaveClient.js
=> fix: update node groups on node ready

app.js, src/apis/ConfigApis.js, src/components/Confirm.vue, src/components/Store.vue
https://user-images.githubusercontent.com/11502495/115395148-d948b100-a1e3-11eb-850c-d4b186724e1f.mp4
=> feat(ui): create new directory/files in store

src/components/ValueId.vue
=> fix(ui): valueid label color

lib/ZwaveClient.js
Ref: https://github.com/zwave-js/node-zwave-js/pull/2406, needs new zwave-js release
=> feat: allow loading custom device configs from `store/config`

docker/README.md, docker/docker-compose.yml, lib/SocketManager.js, lib/ZwaveClient.js, src/App.vue, src/plugins/socket.js, src/store/mutations.js, types/index.d.ts
ZwaveClient will automatically check for updates at midnight and the user can trigger a check/install directly from the UI
=> feat: zwave-js config updates

src/components/nodes-table/ExpandedNode.vue, types/index.d.ts
=> fix(ui): hide hass tab when gw is disabled

src/App.vue
=> fix(ui): pretty json exports

docker/Dockerfile
=> fix(docker): config update not working

docker/Dockerfile, docs/guide/env-vars.md
=> chore(docker): adding missing env var to base image

lib/ZwaveClient.js, src/components/nodes-table/index.vue
Fixes https://github.com/zwave-js/node-zwave-js/issues/2600
=> fix: battery devices not ready

src/components/nodes-table/NodeDetails.vue
Preview of the change:
Fixes #1086
=> fix(ui): moved Value Refresh button to right on NodeDetails

app.js, src/components/nodes-table/AssociationGroups.vue
=> fix(ui): group editors showing associations of last expanded node

src/components/dialogs/DialogAssociation.vue
=> fix(ui): show group id in dialog dropdown

src/components/Mesh.vue, src/components/custom/ZwaveGraph.vue
=> fix(ui): zwave graph better detection of neighbors changes

lib/ZwaveClient.js
Fixes #1246
Fixes https://github.com/zwave-js/node-zwave-js/issues/2609
=> fix: detect driver failed and restart

docs/guide/mqtt.md, lib/ZwaveClient.js, types/index.d.ts
=> fix: better restarts

lib/SocketManager.js, lib/ZwaveClient.js, src/components/ControlPanel.vue, src/components/nodes-table/index.vue, src/components/nodes-table/nodes-table.js, src/plugins/socket.js, src/store/mutations.js
Fixes #993
https://user-images.githubusercontent.com/11502495/119520017-33580b80-bd7a-11eb-916e-e1bac5c40dbf.mp4
=> feat(ui): show nodes heal progress

lib/ZwaveClient.js, src/components/Mesh.vue, src/store/mutations.js
CC @AlCalzone. Fixes https://github.com/zwave-js/node-zwave-js/issues/2493
=> fix: don't query neighbors on node ready event

lib/ZwaveClient.js
Reference: https://github.com/zwave-js/node-zwave-js/issues/2493
Introduced by: https://github.com/zwave-js/node-zwave-js/pull/2636
=> fix: stop RF when requesting neighbors

src/components/ValueId.vue
=> fix(ui): use strict check in toggle button

hass/configurations.ts
=> fix(hass): broken cover discovery

docker/Dockerfile.contrib
Fixes #1325 
@larstobi Feedback?
=> chore(docker): fix Dockerfile.contrib for custom builds

package.json, yarn.lock
=> fix: downngrade to serialport@9.0.7

lib/Gateway.ts
=> fix(discovery): skip discovery of notifications without states

package.json, yarn.lock
=> fix: downgrade pkg@4.4.9

hass/devices.ts
#1331 was not complete IMHO. There was one other reference which wasn't updated upon closer inspection.
=> fix: entry in hass/devices.ts for cover discovery

docker/Dockerfile, docker/Dockerfile.contrib
=> chore(docker): bump node to 16.3.0

hass/configurations.ts
Fixes #1343
Fixes #830 
cc @darootler @bushvin
=> fix(hass): remove state_topic from covers

docs/index.html
Fix https://github.com/zwave-js/node-zwave-js/issues/2868
=> docs: fix namespace error

src/components/nodes-table/nodes-table.js
=> feat(ui): zwave plus column

docs/guide/nodes-management.md
The description wasn't exactly accurate
=> docs: correct removing and replacing failed nodes

lib/ZwaveClient.ts
=> fix: send heal node status when healing single node

docs/development/intro.md
based on questions I've seen recently.
=> docs: improve docs for testing device configurations

lib/ZwaveClient.ts
=> fix: sending 'start' or 'stop' MultilevelSwitchCC not working

hass/configurations.ts
=> fix(hass): add default to central_scene

hass/configurations.ts
Per some unexpected breakage documented in #1360.
=> fix(hass): revert #1360 "make dimmers turn on to previous brightness"

.github/workflows/release-it.yml, package.json, package.sh, yarn.lock
Needs https://github.com/vercel/pkg/issues/1192 fixed. Maybe in pkg@5.2.2
=> chore: use pkg@5.2.1 and fix package.sh/workflow

lib/Gateway.ts
=> fix: ensure subscribe to topics

docs/development/intro.md, lib/ZwaveClient.ts
=> feat: add `deviceConfig` to node

hass/configurations.ts, lib/Gateway.ts
=> fix(hass): barrier operator CC MQTT discovery

.github/workflows/ci.yml
=> chore: fix bot lint

hass/configurations.ts
Added missing `command_topic`. Fixes #1363
=> fix(hass): discovery of Barrier State CC

docs/usage/setup.md, src/components/Settings.vue
=> feat(ui): auto-format OZW keys when pasted into security keys

app.ts, lib/ZwaveClient.ts, package.json, src/components/Settings.vue, src/store/mutations.js, yarn.lock
=> feat: add `deviceConfigPriorityDir` zwave setting

docs/guide/env-vars.md, lib/logger.ts, package.json, src/components/Settings.vue, src/store/mutations.js
`Z2M_LOG_MAXFILES` and `Z2M_LOG_MAXSIZE` env vars can be used to override defaults settings
Fixes #1158
=> feat: log rotate

build/webpack.base.conf.js, package.json, yarn.lock
=> chore: fix icons font not loading when using nginx

app.ts
Fixes #1762
cc @jmgiaever could you give it a try?
=> fix: ignore ZWAVEJS_EXTERNAL_CONFIG folder

src/components/nodes-table/index.vue, src/components/nodes-table/nodes-table.js
Colors was common html colors, I put the colors for vuetify theme for better UX.
=> feat(ui): use theme color for icon in table

.github/workflows/docker-release.yml
=> chore(docker): undo signing for now

docker/docker-compose.yml, docs/getting-started/docker.md
=> docs: add note about port mapping to docker instructions

lib/ZwaveClient.ts
=> fix: correctly set node name and location when present on provisioning

src/components/SmartStart.vue
=> fix(ui): provisioning info lost when editing an entry

app.ts, src/components/Confirm.vue, src/components/Settings.vue
Fixes #1947 
Fixes #1936
Needs: https://github.com/gruhn/vue-qrcode-reader/pull/279 for all camera support
=> feat: add HTTPS setting and Qr improvements

lib/ZwaveClient.ts
=> fix: value not updating after set

src/components/SmartStart.vue
=> fix(ui): spelling of Unauthenticated

src/components/dialogs/DialogAddRemove.vue
=> fix(ui): typo in dialog

docs/README.md
See also https://www.domoticz.com/wiki/ZwaveJS2MQTT
=> docs: added Domoticz as application using the MQTT Discover function.

lib/ZwaveClient.ts, src/App.vue, src/components/Settings.vue, src/components/dialogs/DialogAddRemove.vue
=> feat: show driver errors on UI and prevent restart when zwave options are not valid

lib/ZwaveClient.ts, src/components/ControlPanel.vue, src/components/custom/BlinkIcon.vue, src/components/nodes-table/index.vue, src/components/nodes-table/nodes-table.js, src/lib/utils.js, src/store/mutations.js
=> feat(ui): add active indicator with statistics tooltip

src/store/mutations.js
=> fix: set zwave logs enabled by default

package.json
=> chore: add zwavejs config db to pkg executable

lib/ZwaveClient.ts, src/components/nodes-table/index.vue, src/components/nodes-table/nodes-table.js
=> feat(ui): visualize running firmware updates

src/components/ControlPanel.vue, src/components/nodes-table/nodes-table.js
=> fix(ui): drop `failed` column

.mergify.yml
@chrisns could you give this a check please? 
https://blog.mergify.com/strict-mode-deprecation/
=> chore: fix mergify bot

lib/ZwaveClient.ts, src/components/nodes-table/NodeDetails.vue
=> feat(ui): add cc version

lib/ZwaveClient.ts
=> fix: restart driver after hard reset

lib/ZwaveClient.ts
=> fix: ensure node is ready before getting cc version

lib/ZwaveClient.ts, src/components/dialogs/DialogAddRemove.vue
=> feat: set node name and location before inclusion and keep `nodes.json` up to date

.vscode/settings.json, src/components/nodes-table/ExpandedNode.vue, src/components/nodes-table/NodeDetails.vue
=> feat(ui): move inclusion information to separete tab

lib/SocketManager.ts, lib/ZwaveClient.ts, package.json, src/components/Mesh.vue, src/components/custom/StatisticsArrows.vue, src/components/custom/ZwaveGraph.vue, src/components/dialogs/DialogHealthCheck.vue, src/components/nodes-table/AssociationGroups.vue, src/components/nodes-table/index.vue, src/components/nodes-table/nodes-table.js, src/plugins/socket.js, yarn.lock
=> feat: implement health reporting

lib/ZwaveClient.ts
=> fix: inclusion with name and location not working sometimes

src/components/Mesh.vue, src/components/custom/ZwaveGraph.vue
=> feat(ui): allow to filter nodes in mesh graph

lib/ZwaveClient.ts
As described in this Issue from node-zwave-js:
https://github.com/zwave-js/node-zwave-js/issues/4064
=> fix(hass): support for Multi Level Switch Start and Stop CC

app.ts, config/store.ts, lib/Gateway.ts, lib/ZwaveClient.ts, lib/jsonStore.ts, test/lib/jsonStore.test.ts
=> fix: ensure settings contains default and do not throw errors

app.ts, docker/Dockerfile.contrib, lib/ZwaveClient.ts, package.json, src/components/Confirm.vue, src/components/Mesh.vue, src/components/Settings.vue, src/components/Store.vue, src/components/custom/StatisticsArrows.vue, src/components/custom/ZwaveGraph.vue, src/components/dialogs/DialogGatewayValue.vue, src/components/dialogs/DialogSceneValue.vue, src/components/nodes-table/index.vue, src/lib/utils.js, src/store/mutations.js, yarn.lock
=> feat: bump zwave-js@9 and @zwave-js/server@1.16.0 and fix breaking changes (#2294)

docker/Dockerfile
=> fix(docker): serialport bindings issue

.yarnrc.yml
…he "can't be found in the cache and will be fetched from the remote registry" one
=> chore: make build logs quieter

src/components/SmartStart.vue
Corrected misspelling of "Unhauthenticated" to "Unauthenticated"
=> fix(ui): correct misspelling

lib/ZwaveClient.ts
=> fix: correctly parse MultilevelSwitchCC notifications

lib/ZwaveClient.ts
=> fix: inclusion via QR forgets name/location

lib/ZwaveClient.ts, package.json, src/components/Confirm.vue, src/components/SmartStart.vue, src/lib/utils.js, yarn.lock
cc @AlCalzone @kpine 
Fixes #2274
=> feat: active status and disable non requested security classes in provisioning entities

lib/MqttClient.ts, lib/utils.ts
=> fix: correctly parse buffers in MQTT payload

src/modules/ManagedItems.js
=> fix(ui): table sorting/grouping with undefined values

docs/guide/env-vars.md, lib/logger.ts
=> feat: allow to disable logs with `NO_LOG_COLORS` env var

lib/SocketEvents.ts, lib/ZwaveClient.ts, lib/utils.ts, src/App.vue, src/components/Login.vue, src/components/Settings.vue, src/components/nodes-table/ExpandedNode.vue, src/lib/utils.js, src/plugins/vuetify.js, src/store/mutations.js
This can be useful expecially to detect node notifications and all other events that are not shown on UI
https://user-images.githubusercontent.com/11502495/170527755-33a39042-23d5-4aec-a324-bb068d54dd64.mp4
=> feat(ui): node events logs queue

src/components/Debug.vue
=> fix(ui): show warning when zwave or general logs are disabled

lib/logger.ts
=> fix: log rotation

lib/ZwaveClient.ts, src/components/nodes-table/NodeDetails.vue, yarn.lock
=> fix: issues with controller powerlevel settings

app.ts, docs/guide/env-vars.md, docs/usage/setup.md, lib/ZwaveClient.ts, src/components/Settings.vue
=> feat: allow to force disable SSL

src/components/nodes-table/OTAUpdates.vue
Fixed a typo in loading text caption
=> fix(ui): typo in ota update tab

lib/ZwaveClient.ts, src/components/nodes-table/OTAUpdates.vue
=> fix(ui): firmware update changelog overflow

src/components/nodes-table/NodeDetails.vue
=> fix(ui): refreshing RF region results in empty field

src/components/nodes-table/ExpandedNode.vue
=> fix(ui): hide useless actions from controller node

.eslintignore, app.ts, config/app.ts, lib/ZwaveClient.ts, package.json, snippets/clone-config.js, src/apis/ConfigApis.js, src/components/Confirm.vue, src/components/ControlPanel.vue, src/components/Store.vue
=> feat: driver function snippets

lib/ZwaveClient.ts
=> feat: set zwave-js `userAgent` option

docs/guide/env-vars.md, lib/Gateway.ts
=> feat: add `UID_DISCOVERY_PREFIX` env var

lib/ZwaveClient.ts, package.json, src/components/ControlPanel.vue, src/components/nodes-table/ExpandedNode.vue, src/components/nodes-table/OTAUpdates.vue, src/lib/utils.js, yarn.lock
=> feat: zwave-js@10.3.0 and new fw update apis

package.json, src/App.vue, src/components/Confirm.vue, src/components/ControlPanel.vue, src/components/Debug.vue, src/components/Login.vue, src/components/Mesh.vue, src/components/Scenes.vue, src/components/Settings.vue, src/components/SmartStart.vue, src/components/Store.vue, src/components/nodes-table/AssociationGroups.vue, src/components/nodes-table/NodeDetails.vue, src/components/nodes-table/OTAUpdates.vue, src/store/mutations.js, yarn.lock
=> feat(ui): better snackbars and import provisioning json

src/components/dialogs/DialogNodesManager.vue
- More obivious inclusion timeout. Fixes #2079
- Prevent hanging indeterminately when node added event is not trigger for some reason. Fixes #2746
- Disable go back while inclusion is running. Fixes #2735
=> fix(ui): nodes manager dialog improvements

lib/ZwaveClient.ts, src/components/nodes-table/index.vue, src/components/nodes-table/nodes-table.js
Ref: https://github.com/zwave-js/node-zwave-js/issues/5167
=> fix(ui): better firmware update progress

src/components/nodes-table/OTAUpdates.vue
I found that I checked the "OTA Updates" but that I actually didn't know what the "No updates available" meant - because I _know_ that there are updates for this device. So I checked, and found old threads etc, but to help future me (and others), I'm making this update :)
=> feat(ui): add notice on OTA updates not being complete

lib/ZwaveClient.ts, lib/logger.ts
Fixes [#782](https://github.com/zwave-js/zwave-js-server/issues/782)
=> fix: catch zwave js server errors

lib/ZwaveClient.ts, src/components/nodes-table/OTAUpdates.vue
=> feat(ui): allow to fetch OTA pre-releases

lib/ZwaveClient.ts, src/components/ValueId.vue, src/stores/base.js
Ref: https://github.com/zwave-js/zwave-js-ui/issues/188#issuecomment-1295987999
=> feat(ui): show loader when value is waiting an update

lib/Gateway.ts, lib/ZwaveClient.ts
=> fix(mqtt): node added on fly not subscribed to changes

src/components/nodes-table/NodeDetails.vue
=> feat(ui): add value format to Custom ConfigCC

lib/ZwaveClient.ts
=> feat(mqtt): add mqtt support for inclusion callbacks

lib/Constants.ts, lib/Gateway.ts
Addresses most of the issues described in "Incorrect device classes and measurement units now a problem with HA 2023.1.1 
Fixes #2877
=> fix(discovery): errors with electricity device_class and HA 2023.1

docs/usage/setup.md, lib/Gateway.ts, snippets/pingNodes.js, src/components/Settings.vue, src/stores/base.js
=> feat: scheduled jobs

docs/guide/mqtt.md, lib/Gateway.ts, lib/ZwaveClient.ts
=> feat(mqtt): add node `lastActive` topic

package.json, yarn.lock
unblocks https://github.com/zwave-js/zwave-js-ui/pull/2879
=> feat: bump zwave-js-server@1.25.0

lib/ZwaveClient.ts, lib/utils.ts, src/views/Debug.vue
=> feat: standardize node id in logs and filter in debug view

lib/ZwaveClient.ts, package.json, src/components/dialogs/DialogAssociation.vue, src/components/nodes-table/AssociationGroups.vue, src/views/ControlPanel.vue, yarn.lock
Removed `endpointIndezes` in favor of `endpoint` property from ZUINode
=> feat: zwave-js@10.7.0, heal network options, endpoints labels (#2941

src/views/Store.vue
=> fix(ui): prismjs editor line numbers (#2947

.github/workflows/ci.yml
Include node 19 in unit testing
=> chore: include node 19 in unit tests

lib/ZwaveClient.ts
=> fix: prevent fw updates when update in progress

lib/SocketEvents.ts, lib/ZwaveClient.ts, package.json, src/components/dialogs/DialogNodesManager.vue, src/components/nodes-table/ExpandedNode.vue, src/stores/base.js, src/views/ControlPanel.vue, yarn.lock
=> fix: broken inclusion process (#2995

lib/ZwaveClient.ts, package.json, src/components/custom/BgRssiChart.vue, src/components/custom/StatisticsArrows.vue, src/router/index.js, src/stores/base.js, src/views/ControllerChart.vue, src/views/Mesh.vue, yarn.lock
Fixes #3008
Network Graph > Controller >
=> feat: background RSSI chart (#3033)Co-authored-by: Dominic Griesel <dominic.griesel@nabucasa.com>

.vscode/settings.json, lib/SocketEvents.ts, lib/ZwaveClient.ts, src/App.vue, src/stores/base.js
=> fix: valueId metadata out of sync with ui

.vscode/settings.json, docs/getting-started/docker.md
=> docs: add healtcheck docs

package.json, yarn.lock
I'm guessing you will know what I would ask for as part of this PR 🙂
=> feat: bump zwave-js/server@1.28.0

.gitignore, lib/ZwaveClient.ts, src/components/nodes-table/NodeDetails.vue, src/components/nodes-table/UserCodeTable.vue
=> feat(ui): user codes management

lib/ZwaveClient.ts, lib/utils.ts, src/components/Confirm.vue, src/components/nodes-table/ExpandedNode.vue, src/components/nodes-table/NodeScheduler.vue, src/lib/utils.js
=> feat(ui): support for Schedule Entry Lock CC

lib/ZwaveClient.ts, package.json, src/components/nodes-table/ExpandedNode.vue, src/components/nodes-table/NodeDetails.vue, src/components/nodes-table/NodeScheduler.vue, src/components/nodes-table/SmartView.vue, src/components/nodes-table/UserCodeTable.vue, yarn.lock
=> fix: improve schedule lock entry cc query to prevent spam

app.ts, lib/SocketManager.ts, lib/ZwaveClient.ts, src/App.vue, src/components/dialogs/DialogNodesManager.vue, src/stores/base.js, src/views/ControlPanel.vue
=> feat: better user callbacks management with HA

lib/ZwaveClient.ts
=> feat: exponential backoff when restarting driver

lib/ZwaveClient.ts, src/components/dialogs/DialogHealthCheck.vue
=> feat: allow to abort health checks and show steps results

lib/ZwaveClient.ts, src/components/nodes-table/NodeDetails.vue, src/lib/items.js, src/lib/utils.js, src/stores/base.js, src/views/Settings.vue
=> feat: add new controller rfregion and txpower settings

lib/ZwaveClient.ts, src/components/custom/ReinterviewBadge.vue, src/components/nodes-table/SmartView.vue, src/components/nodes-table/index.vue, src/components/nodes-table/nodes-table.js
=> feat(ui): show when devices needs to be re-interviewed

lib/ZwaveClient.ts, src/components/custom/ReinterviewBadge.vue, src/components/nodes-table/SmartView.vue, src/components/nodes-table/index.vue
=> fix(ui): hide config update badge after re-interview

lib/ZwaveClient.ts
=> feat: show controller status

app.ts
=> fix: auto redirect when using old paths

src/components/nodes-table/SmartView.vue, src/components/nodes-table/index.vue, src/components/nodes-table/nodes-table.js
=> fix(ui): missing `Heal` references in control panel

lib/ZwaveClient.ts, src/views/ControlPanel.vue
=> feat: allow to restore NVM raw

src/components/nodes-table/OTAUpdates.vue
=> fix(ui): hide OTA downgrades by default and fix icon

app.ts, src/App.vue
=> feat: parse multiple releases in changelogs

src/App.vue, src/stores/base.js
=> fix(ui): theme not persisted correctly

lib/Gateway.ts
=> fix: scheduled jobs not running when mqtt disabled

lib/ZwaveClient.ts, src/components/nodes-table/OTAUpdates.vue
=> feat(ui): parse fw OTA changelog

.dockerignore, docker/Dockerfile
=> fix(docker): skip install when node_modules is present

src/components/nodes-table/SmartView.vue
=> feat(ui): compact view sort

.github/workflows/package_arm64.yml, esbuild.js, package.json, package.sh
=> chore: use esbuild bundle in pkg

package-lock.json, package.json
=> fix: move optional deps to dev dependencies

src/views/ControlPanel.vue
=> feat(ui): show node info in fw update dialog

src/App.vue, src/views/ErrorPage.vue
=> fix(ui): ensure all changelog links open on new tab

.env.app.example, api/app.ts, docs/guide/env-vars.md, src/App.vue, src/components/custom/StatisticsArrows.vue, src/components/nodes-table/ExpandedNode.vue, src/stores/base.js, src/views/SmartStart.vue
Fixes #3524 
Fixes #3013
Fixes #2721
=> feat(ui): custom browser TZ/LOCALE and UI persistent preferences

api/lib/ZwaveClient.ts, src/App.vue
=> feat: show inclusion state on UI

.gitignore, src/App.vue, src/apis/ConfigApis.js, vite.config.js
=> fix(ui): ignore `**/api/**` from service worker cache

api/lib/Gateway.ts, api/lib/ZwaveClient.ts, docs/guide/mqtt.md, genereteDocs.ts
=> feat(mqtt): allow to set options in multicast/broadcast requests

api/lib/Gateway.ts
=> fix(discovery): revert "improve MQTT discovery for scene CC"

src/components/custom/ZwaveGraph.vue
=> fix(ui): show nlwr route when lwr is unknown in overview

src/components/nodes-table/index.vue, src/components/nodes-table/nodes-table.js
=> feat(ui): search box in control panel table

api/lib/ZwaveClient.ts
=> fix: keep node name and location in sync

docs/usage/setup.md
docs: Added description about config switch
=> docs: added small info about configuration

src/components/dialogs/DialogAssociation.vue, src/components/nodes-table/AssociationGroups.vue, src/components/nodes-table/ExpandedNode.vue
=> fix(ui): groups associations for LR nodes

package-lock.json, package.json
No real changes from the beta but just to keep up with the latest :)
=> feat: bump @zwave-js/server to 1.35.0

api/lib/ZwaveClient.ts, docs/guide/mqtt.md, package.json, src/components/nodes-table/ExpandedNode.vue, src/mixins/InstancesMixin.js
=> feat: add dump node action

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/discord-publish.yml, .github/workflows/docker-release-test.yml, .github/workflows/docker-test.yml, .github/workflows/package_arm64.yml, .github/workflows/package_armv7.yml, .github/workflows/release-it.yml, .github/workflows/update-dep.yml, .github/workflows/zwave-js-bot_comment.yml
=> chore: fix arm build

package-lock.json, package.json, src/components/dialogs/DialogLinkReliability.vue
13.0.2 makes some breaking changes to the link check stuff. This PR fixes it.
=> feat: support link check modifications in zwave-js 13.0.2

src/stores/base.js, src/views/Settings.vue
=> feat(ui): add streamer mode setting to hide sensitive informations

src/views/Mesh.vue
=> fix(ui): improve network graph popup visibility

api/lib/logger.ts, package-lock.json, package.json
=> fix: remove obsolete @zwave-js/winston-daily-rotate-file in favor of original package

src/views/Zniffer.vue
=> fix(ui): routed ack frames row style

api/app.ts, api/lib/ZwaveClient.ts, api/lib/logger.ts, package-lock.json, package.json, src/views/Debug.vue, test/lib/logger.test.ts
=> feat: always show driver/app logs on debug UI even when log settings are disabled

api/lib/Gateway.ts
=> fix(discovery): improve covers discovery

api/lib/Gateway.ts
And for scene values, use the correct template because the value is a JSON object that also includes the units, but nests the actual value one level deeper.
=> fix(discovery): define units for scene and configuration values

api/hass/configurations.ts, api/lib/Gateway.ts
=> fix(discovery): correctly handle up/down commands for covers

package.json
fix build script on windows as discussed here: https://github.com/zwave-js/zwave-js-ui/issues/3591#issuecomment-1954878183
=> chore: fix build script on windows

docs/guide/plugins.md
Small PR - commit fe7a2c5a2a5c0b5ef761b5b8bb05f774dd4a2c61 moved the location of the `CustomPlugin.ts` script. This PR adjusts sources to changes.
=> docs: update `CustomPlugin.ts` reference

src/components/nodes-table/OTAUpdates.vue
Fixes #3982 Ref https://github.com/zwave-js/node-zwave-js/pull/7369
=> feat(ui): allow to specify rf region in OTA fw updates when it's unknown

package-lock.json, package.json
fixes: https://github.com/zwave-js/zwave-js-ui/issues/3997
fixes: https://github.com/zwave-js/zwave-js-ui/issues/3994
=> fix: bump zwave-js to 14.3.2

api/lib/ZwaveClient.ts
fixes: https://github.com/zwave-js/zwave-js-ui/issues/4006
=> fix: save value change options on ZWaveNode instance

.mergify.yml
This change has been made by @robertsLando from the Mergify config editor.
=> ci(mergify): configuration update

docs/README.md
this could make or break the project tbh
=> docs: fix typo

api/lib/Gateway.ts, src/components/dialogs/DialogGatewayValue.vue
=> feat(mqtt-discovery): gateway values setting to enable by default Configuration CC entities

src/views/Zniffer.vue
=> feat(ui): show full date when hovering timestamp on zniffer

api/lib/PkgFsBindings.ts, api/lib/ZwaveClient.ts, package.json
fixes: https://github.com/zwave-js/zwave-js-ui/issues/4156
=> fix: config sync inside `pkg` binaries

package-lock.json, package.json
fixes: https://github.com/zwave-js/zwave-js-ui/issues/4162
=> feat: bump zwave-js@15.0.2 to fix enum `Indicator` not defined in `pkg` bundle

api/lib/PkgFsBindings.ts
=> fix: normalize paths for pkg on Windows

api/lib/MqttClient.ts, api/lib/utils.ts
=> fix: correct serialization of Uint8Array in MQTT messages

api/lib/ZwaveClient.ts, src/App.vue
=> fix: otw update and node firmware update progress hangs on finish

src/components/ValueId.vue
=> feat(ui): validate number inputs against min/max from config

.github/bot-scripts/classifyIssueFeedback.cjs, .github/bot-scripts/index.js, .github/workflows/zwave-js-bot_issue.yml
This is an attempt at helping users find the correct repo, specifically the driver repo if they don't have UI issues.
=> ci: help users find the correct repository for issues using AI

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/discord-publish.yml, .github/workflows/docker-release-test.yml, .github/workflows/docker-release.yml, .github/workflows/docker-test.yml, .github/workflows/package_armv7.yml, .github/workflows/package_x64.yml, .github/workflows/release-it.yml, .github/workflows/test-application.yml, .github/workflows/test_install_arm64.yml, .github/workflows/update-dep.yml, .github/workflows/zwave-js-bot_comment.yml, .github/workflows/zwave-js-bot_issue.yml, .release-it.json
This pull request updates the project's GitHub Actions workflows to use the latest versions of key actions, improving security, reliability, and compatibility. It also introduces a new workflow for building and testing x64 packages, and removes a deprecated release hook from the release configuration.
**CI/CD Workflow Updates:**
* Updated all uses of `actions/checkout` from v4 to v5 in workflow files for improved performance and security. [[1]](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL23-R26) [[2]](diffhunk://#diff-63bd641104d10e25f141d518a16b22a151d125e12701df2f9e79734b23b90188L22-R22) [[3]](diffhunk://#diff-db209efba16a4a2772a3ebbc8e64c618217b62d0005dd04360c72c6f7dcbce06L14-R16) [[4]](diffhunk://#diff-a886d4839cd45b672cdbba872da1d5c6d7a5c0ee218eb2 …
=> chore: bump actions and add packages tests
